title: Kalyan Parajuli
author: Kalyan Parajuli
url: https://krparajuli.com # root address of the site
description: | # description of the site (multiple lines allowed)
              I am a motivated and multi-talented **Security Engineer** with a background in **Software Engineering and Cloud Technologies** w/ AWS, GCP 
              and Akamai Cloud. I have built numerous automations in and around security products and configurations using Python and Golang. 
              I am well versed in Infrastructure-as-Code and have managed AWS Infrastructure in a medium sized company. I possess good knowledge of security
              protocols, practices, and tools - which allows me to contribute to security discussion and architecture of various products. I am also
              an avid home-labber, and engage in **Threat Intel, Malware Reversing, and Application Security** in my free time. I also engage with
              and mentor students at my alma mater and in my hometown in Nepal in the field of cybersecurity

permalink: /:slug

favicon: "./logo.png" # relative path to site's favicon

twitter:
    username: entropiqor # update or delete this
    card: summary_large_image

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  back_home_text: "Home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: false # show footer links in home page,add in _data/home.yml
  show_copyright: false # show copyright notice in footer
  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: false # show blog posts added in _posts
  show_old_projects: false # show old projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml
  show_reading_time: true # show number of words and reading time in the blog posts
  show_tags: true # show tags in a blog posts
  # options for "home" page
  home:
    title_projects: Portfolio
    title_misc_list: Details
    title_blog: Blog
    title_old_projects: Old Projects

soopr:
  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
